# Generated by Django 5.1.15 on 2026-07-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_hash', models.CharField(db_index=True, max_length=64)),
                ('source_text', models.TextField()),
                ('target_lang', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['string_hash', 'target_lang'], name='translator__string__7af2a8_idx')],
                'unique_together': {('string_hash', 'target_lang')},
            },
        ),
    ]
