# Generated by Django 5.1.15 on 2026-07-10 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('candidate', 'Candidate'), ('member', 'Party Member')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('riding_name', models.CharField(max_length=255)),
                ('riding_number', models.CharField(blank=True, max_length=20)),
                ('mp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mp_party', models.CharField(blank=True, max_length=100, null=True)),
                ('mpp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mpp_party', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('candidate_bio', models.TextField(blank=True)),
                ('candidate_url', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['province', 'riding_name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('experience', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_pages.certification')),
            ],
        ),
    ]
