# Generated by Django 5.1.15 on 2026-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_filename', models.CharField(help_text='Filename from static/assets/img/ or media/', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-delimited keywords for filtering', max_length=500)),
                ('links_json', models.TextField(blank=True, help_text='JSON array of {label, url} objects')),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
