# Generated by Django 5.1.15 on 2026-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_pages', '0002_stat_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAOHAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('anchor', models.CharField(help_text="Anchor ID (e.g., 'immigration', 'fertility')", max_length=500)),
                ('url', models.URLField(help_text='Full URL to the WAOH anchor', max_length=1000)),
                ('category', models.CharField(blank=True, help_text='Category from WAOH index', max_length=200)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('anchor', 'url')},
            },
        ),
    ]
