# Generated by Django 5.1.15 on 2026-08-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_pages', '0003_waoh_anchor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='waohanchor',
            name='stat_image',
            field=models.ForeignKey(blank=True, help_text='Matched stat image by anchor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='party_pages.statimage'),
        ),
    ]
