# Generated by Django 5.1.15 on 2026-08-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_pages', '0004_waoh_anchor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='riding',
            name='candidate_certification',
            field=models.CharField(blank=True, choices=[('', 'None'), ('trainee', 'Trainee'), ('graduate', 'Professional Civic Scientist')], default='', help_text="Certification level from the official's dashboard profile", max_length=20),
        ),
        migrations.AddField(
            model_name='riding',
            name='director_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riding',
            name='director_photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='riding',
            name='director_role',
            field=models.CharField(blank=True, default='Riding Director', max_length=120),
        ),
        migrations.AddField(
            model_name='riding',
            name='treasurer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riding',
            name='treasurer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='riding',
            name='treasurer_role',
            field=models.CharField(blank=True, default='Treasurer', max_length=120),
        ),
    ]
