# Generated by Django 5.1.15 on 2026-09-06 16:29

from django.db import migrations, models


def purge_placeholder_candidates(apps, schema_editor):
    # The seeded riding data shipped with invented candidate names
    # (e.g. "Nora MacDonald" — the Governor General and a Liberal appointee)
    # that never belonged to the Advance Party. None are real candidates, so
    # blank every candidate field; the /candidates page shows an empty
    # "Advance Candidate" cell for ridings with no candidate running.
    Riding = apps.get_model('party_pages', 'Riding')
    Riding.objects.update(
        candidate_name=None,
        candidate_photo=None,
        candidate_bio='',
        candidate_certification='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('party_pages', '0007_seed_stats_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='riding',
            name='candidate_accepted_at',
            field=models.DateField(blank=True, help_text='Date the candidate was accepted/confirmed', null=True),
        ),
        migrations.AddField(
            model_name='riding',
            name='candidate_accepted_by',
            field=models.CharField(blank=True, default='', help_text='Name of the official who accepted the candidate', max_length=255),
        ),
        migrations.AddField(
            model_name='riding',
            name='candidate_elected',
            field=models.BooleanField(default=False, help_text='Candidate was elected in this riding'),
        ),
        migrations.AddField(
            model_name='riding',
            name='candidate_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('current', 'Current'), ('prior', 'Prior'), ('applied', 'Applied')], default='', help_text='Standing of the candidate named on this riding', max_length=20),
        ),
        migrations.RunPython(purge_placeholder_candidates, migrations.RunPython.noop),
    ]
