# Generated by Django 5.1.15 on 2026-09-07 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DEFAULT_CHART_OF_ACCOUNTS = [
    {'code': '1000', 'name': 'Cash', 'account_type': 'asset', 'normal_balance': 'debit'},
    {'code': '1100', 'name': 'Accounts Receivable', 'account_type': 'asset', 'normal_balance': 'debit'},
    {'code': '1200', 'name': 'Inventory', 'account_type': 'asset', 'normal_balance': 'debit'},
    {'code': '1300', 'name': 'Incorporation & Legal Costs', 'account_type': 'asset', 'normal_balance': 'debit'},
    {'code': '2000', 'name': 'Accounts Payable', 'account_type': 'liability', 'normal_balance': 'credit'},
    {'code': '2100', 'name': 'CSQ Research Donations Payable', 'account_type': 'liability', 'normal_balance': 'credit'},
    {'code': '2300', 'name': 'Customer Deposits', 'account_type': 'liability', 'normal_balance': 'credit'},
    {'code': '3000', 'name': 'Owner / Founder Equity', 'account_type': 'equity', 'normal_balance': 'credit'},
    {'code': '3100', 'name': 'Retained Earnings', 'account_type': 'equity', 'normal_balance': 'credit'},
    {'code': '4000', 'name': 'Donations Revenue', 'account_type': 'revenue', 'normal_balance': 'credit'},
    {'code': '4100', 'name': 'Product / Enrollment Revenue', 'account_type': 'revenue', 'normal_balance': 'credit'},
    {'code': '4200', 'name': 'Membership Revenue', 'account_type': 'revenue', 'normal_balance': 'credit'},
    {'code': '5000', 'name': 'Incorporation & Compliance', 'account_type': 'expense', 'normal_balance': 'debit'},
    {'code': '5100', 'name': 'Marketing & Advertising', 'account_type': 'expense', 'normal_balance': 'debit'},
    {'code': '5200', 'name': 'Software & Hosting', 'account_type': 'expense', 'normal_balance': 'debit'},
    {'code': '5300', 'name': 'Transaction & Processing Fees', 'account_type': 'expense', 'normal_balance': 'debit'},
    {'code': '5400', 'name': 'Salaries & Contractors', 'account_type': 'expense', 'normal_balance': 'debit'},
    {'code': '5500', 'name': 'Legal & Professional Services', 'account_type': 'expense', 'normal_balance': 'debit'},
    {'code': '5900', 'name': 'Other Operating Expenses', 'account_type': 'expense', 'normal_balance': 'debit'},
]


def seed_coa(apps, schema_editor):
    Account = apps.get_model('ledger', 'Account')
    valid = {f.name for f in Account._meta.get_fields()}
    for item in DEFAULT_CHART_OF_ACCOUNTS:
        defaults = {k: v for k, v in item.items() if k != 'code' and k in valid}
        Account.objects.update_or_create(code=item['code'], defaults=defaults)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', help_text='Natural balance side — debit for assets/expenses, credit for liabilities/equity/revenue', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('hub_committed', models.BooleanField(default=False)),
                ('hub_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(seed_coa, migrations.RunPython.noop),
    ]
