# Generated by Django 5.1.15 on 2026-08-10 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('member', 'Party Member'), ('candidate', 'Candidate'), ('riding_director', 'Riding Director'), ('treasurer', 'Treasurer'), ('mpp', 'MPP'), ('mp', 'MP')], default='member', max_length=30)),
                ('certification', models.CharField(blank=True, choices=[('', 'None'), ('trainee', 'Trainee (Professional Civic Scientist in training)'), ('graduate', 'Professional Civic Scientist (graduate)')], default='', help_text='Certified Professional Civic Scientist trainee or graduate status', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
