# Generated by Django 5.1.15 on 2026-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('president_ab', 'President AB'), ('president_bc', 'President BC'), ('president_mb', 'President MB'), ('president_nb', 'President NB'), ('president_nl', 'President NL'), ('president_ns', 'President NS'), ('president_nt', 'President NT'), ('president_nu', 'President NU'), ('president_on', 'President ON'), ('president_pe', 'President PE'), ('president_qc', 'President QC'), ('president_sk', 'President SK'), ('president_yt', 'President YT'), ('prime_minister', 'Prime Minister'), ('premier', 'Premier'), ('leader_opposition', 'Leader of the Opposition'), ('mpp_leader', 'MPP Leader'), ('mp_leader', 'MP Leader'), ('member', 'Party Member'), ('candidate', 'Candidate'), ('riding_director', 'Riding Director'), ('treasurer', 'Treasurer'), ('mpp', 'MPP'), ('mp', 'MP')], default='member', max_length=30),
        ),
    ]
